# JPA/H2
spring.datasource.url=jdbc:h2:mem:estoredb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/estore_reviews

# Server
server.port=9090

# Security (JWT Config - to be used in code)
estore.jwt.secret=9a4f434241454247424a424b424c424d424e424f425042514252425342544255
estore.jwt.expiration=86400000
